In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3,4,5],[1,2,3,4,5]],dtype=int)
print(a)


[[1 2 3 4 5]
 [1 2 3 4 5]]


In [3]:
print(type(a))

<class 'numpy.ndarray'>


In [4]:
print(len(a))

2


In [5]:
print(a.ndim)

2


In [6]:
print(a.shape)

(2, 5)


In [9]:
a1=a.reshape(2,5)
print(a1)
print(a1.shape)

[[1 2 3 4 5]
 [1 2 3 4 5]]
(2, 5)


In [7]:
print(a)
a2=a.reshape(5,-1)
print(a2)

[[1 2 3 4 5]
 [1 2 3 4 5]]
[[1 2]
 [3 4]
 [5 1]
 [2 3]
 [4 5]]


In [8]:
print(len(a2))
print(a2.ndim)

5
2
