In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3,4,5],[1,2,3,4,5]],dtype=int)
print(a)


[[1 2 3 4 5]
 [1 2 3 4 5]]


In [3]:
print(type(a))

<class 'numpy.ndarray'>


In [4]:
print(len(a))

2


In [5]:
print(a.ndim)

2


In [6]:
print(a.shape)

(2, 5)


In [9]:
a1=a.reshape(2,5)
print(a1)
print(a1.shape)

[[1 2 3 4 5]
 [1 2 3 4 5]]
(2, 5)


In [7]:
print(a)
a2=a.reshape(5,-1)
print(a2)

[[1 2 3 4 5]
 [1 2 3 4 5]]
[[1 2]
 [3 4]
 [5 1]
 [2 3]
 [4 5]]


In [8]:
print(len(a2))
print(a2.ndim)

5
2


In [14]:
%%time
l1 = [1,2,3,4,5]
l2 = [2,3,4,5,6]
l3 = [9,7,6,8,9]

mul_l = np.array([l1,l2,l3],dtype=int)
#print(mul_l.shape)
mul_l = mul_l.reshape(1,15)
print(mul_l.shape)
print(mul_l)

(1, 15)
[[1 2 3 4 5 2 3 4 5 6 9 7 6 8 9]]
CPU times: total: 0 ns
Wall time: 999 µs


In [15]:
mul_l.shape=(3,5)
print(mul_l)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]


In [20]:
mul_l.shape=(3,5)
print(mul_l)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]


In [21]:
r=range(24)
r

range(0, 24)

In [23]:
a1=np.arange(24)
print(a1)
print(a1.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1


In [24]:
b=a1.reshape(6,2,2)
print(b)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]

 [[20 21]
  [22 23]]]


In [25]:
x=np.array([1,2,3,4,5],dtype=np.int8)
print(x.itemsize)

1


In [26]:
x=np.array([1,2,3,4,5],dtype=np.int16)
print(x.itemsize)
x=np.array([1,2,3,4,5],dtype=np.int32)
print(x.itemsize)
x=np.array([1,2,3,4,5],dtype=np.int64)
print(x.itemsize)

2
4
8


In [27]:
x = np.array([[1,2],[3,4]],dtype = np.float64)
y = np.array([[5,6],[7,8]],dtype = np.float64)
print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [28]:
print(x.itemsize)
print(y.itemsize)

8
8


In [29]:
print(x+y)

[[ 6.  8.]
 [10. 12.]]


In [30]:
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]


In [31]:
print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]


In [32]:
print(x)
print(y)
print(x*y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]
[[ 5. 12.]
 [21. 32.]]


In [33]:
print(np.multiply(x,y)) #simple multiply

[[ 5. 12.]
 [21. 32.]]


In [34]:
print(np.dot(x,y)) # matrix multuplication

[[19. 22.]
 [43. 50.]]


In [35]:
print(x)
print(y)
print(np.divide(x,y))

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [36]:
print(x)
print(np.sum(x))

[[1. 2.]
 [3. 4.]]
10.0


In [37]:
print(np.sum(x,axis=0))

[4. 6.]


In [38]:
print(np.sum(x,axis=1))

[3. 7.]


In [39]:
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [40]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [41]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
np.random.rand(5,5)

array([[0.6149457 , 0.04713365, 0.35517791, 0.46972591, 0.34070042],
       [0.3691087 , 0.50205415, 0.88091276, 0.94950013, 0.26769703],
       [0.4448956 , 0.24014161, 0.89489922, 0.89891473, 0.82310706],
       [0.33971534, 0.57568675, 0.84552857, 0.7453561 , 0.52554888],
       [0.15871394, 0.71995966, 0.26126082, 0.07929398, 0.36761332]])

In [43]:
np.random.randn(5)


array([-0.12269327, -0.80156621, -0.76600749,  0.43213058, -1.54478014])

In [44]:
np.random.randint(1,100,10)


array([65, 80,  6, 37, 53, 69, 61, 46, 95, 39])

In [45]:
arr = np.arange(25)


In [46]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [48]:
ranarr = np.random.randint(0,50,10)


In [49]:
print(ranarr)

[25 12 19 48 35  2 30  2 13 12]


In [50]:
ranarr.max

<function ndarray.max>

In [52]:
print(ranarr.max)

<built-in method max of numpy.ndarray object at 0x0000019B4BFA1950>


In [53]:
ranarr.max()

48

In [54]:
ranarr.min()

2

In [55]:
ranarr.argmin()


5

In [56]:
ranarr.argmax()

3

In [57]:
arr.shape

(25,)

In [58]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [59]:
arr.dtype

dtype('int32')